[uwsgi]
# 项目目录
chdir = /home/admin/my_flask_app

# 虚拟环境路径
venv = /home/admin/my_flask_app/venv

# 启动文件和 Flask 实例名 (app.py 里的 app)
module = app:app

# 是否启动主进程管理
master = true

# 开启多少个工作进程
processes = 4

# 这里的配置很关键：
# 如果是直接测试，用 http = :5000
# 如果配合 Nginx，通常用 socket = 127.0.0.1:8001
http = :5000

# 退出时自动清理环境
vacuum = true
die-on-term = true
